

DEVELOP_PARAMS = {
    'Temperature',
    'Tint',
    'Exposure',
    'Highlights',
    'Shadows',
    'Contrast',
    'Whites',
    'Blacks',
    'Clarity',
    'Vibrance',
    'Saturation',
    -- Tone
    'ParametricDarks',
    'ParametricLights',
    'ParametricShadows',
    'ParametricHighlights',
    'ParametricShadowSplit',
    'ParametricMidtoneSplit',
    'ParametricHighlightSplit',
    
    -- Split Toning
    'SplitToningShadowHue',
    'SplitToningShadowSaturation',
    'SplitToningHighlightHue',
    'SplitToningHighlightSaturation',
    'SplitToningBalance',
    -- Detail
    'Sharpness',
    'SharpenRadius',
    'SharpenDetail',
    'SharpenEdgeMasking',
    'LuminanceSmoothing',
    'LuminanceNoiseReductionDetail',
    'LuminanceNoiseReductionContrast',
    'ColorNoiseReduction',
    'ColorNoiseReductionDetail',
    'ColorNoiseReductionSmoothness',
    -- Mixer
    'SaturationAdjustmentRed',
    'SaturationAdjustmentOrange',
    'SaturationAdjustmentYellow',
    'SaturationAdjustmentGreen',
    'SaturationAdjustmentAqua',
    'SaturationAdjustmentBlue',
    'SaturationAdjustmentPurple',
    'SaturationAdjustmentMagenta',
    'HueAdjustmentRed',
    'HueAdjustmentOrange',
    'HueAdjustmentYellow',
    'HueAdjustmentGreen',
    'HueAdjustmentAqua',
    'HueAdjustmentBlue',
    'HueAdjustmentPurple',
    'HueAdjustmentMagenta',
    'LuminanceAdjustmentRed',
    'LuminanceAdjustmentOrange',
    'LuminanceAdjustmentYellow',
    'LuminanceAdjustmentGreen',
    'LuminanceAdjustmentAqua',
    'LuminanceAdjustmentBlue',
    'LuminanceAdjustmentPurple',
    'LuminanceAdjustmentMagenta',
    'GrayMixerRed',
    'GrayMixerOrange',
    'GrayMixerYellow',
    'GrayMixerGreen',
    'GrayMixerAqua',
    'GrayMixerBlue',
    'GrayMixerPurple',
    'GrayMixerMagenta',
}